import type { CompressionFormat } from './types'

// the platinum seed. ~55 hand-curated formats setting the voice.
// no explainer punchlines. specs are terse and weird. names are real-ish.
// every entry follows the same shape so the renderer is one component.
export const SEED_FORMATS: CompressionFormat[] = [

  // ─────────── TEXT ───────────
  {
    id: 'b-compress',
    name: 'B-Compress',
    blurb: 'roughly 23% of letters become 🅱️',
    mediaType: 'text',
    tags: ['letter-loss', 'b-flavored'],
    spec: `each letter has a 23% chance of becoming 🅱️.
non-letter characters are preserved.
the file gets larger.
the content gets worse.
roughly the only one of these that runs.`,
    ratio: '~1.6× (worse)',
    lossiness: 'destructive',
    status: 'interactive',
    interactiveId: 'b-compress',
    yearProposed: '2017?',
    by: 'r/deepfriedmemes',
    stats: { downloads: '1', stars: '★★★★★ — me', complaints: '0 (no replies)' },
  },
  {
    id: 'yell-algo',
    name: 'YellAlgo',
    blurb: 'lowercase is removed',
    mediaType: 'text',
    tags: ['caps-only', 'removalism'],
    spec: `every lowercase letter is deleted.
spaces are preserved.
files lose roughly 71% of their text.
the remaining text is shouting.`,
    ratio: '~0.29×',
    lossiness: 'lossy',
    status: 'algorithm',
    stats: { stars: '★★★ — they removed my name' },
  },
  {
    id: 'whisper-algo',
    name: 'WhisperAlgo',
    blurb: 'uppercase is removed',
    mediaType: 'text',
    tags: ['lowercase-only', 'inverse-yell'],
    spec: `every uppercase letter is deleted.
the result is somehow more upset than the input.`,
    ratio: '~0.94×',
    lossiness: 'lossy',
    status: 'algorithm',
  },
  {
    id: 'tldr-last',
    name: 'TLDR.txt',
    blurb: 'last word of each sentence',
    mediaType: 'text',
    tags: ['summary', 'reduction'],
    spec: `for each sentence, keep only the last word.
a paragraph becomes a list.
a list becomes a fact.
a fact becomes a fragment.`,
    ratio: 'depends on punctuation',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'tldr-first',
    name: 'TLDR-reversed.txt',
    blurb: 'first word of each sentence',
    mediaType: 'text',
    tags: ['summary', 'opening'],
    spec: `for each sentence, keep only the first word.
the document begins to sound nervous.
it is the same document.`,
    ratio: 'depends',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'monotone-text',
    name: 'MonoTone',
    blurb: 'every word is "one"',
    mediaType: 'text',
    tags: ['flatten', 'pitch-zero'],
    spec: `every word is replaced with the word "one".
punctuation is preserved.
the meaning is preserved exactly.`,
    ratio: '~0.6× (one is short)',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'anagram-zip',
    name: 'AnagramZip',
    blurb: 'each word internally alphabetized',
    mediaType: 'text',
    tags: ['sort-in-place'],
    spec: `each word has its letters sorted in ascending order.
apple becomes aelpp.
the file is the same length.
the file is no longer the file.`,
    ratio: '1× (the size is fine)',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'comma-maximalist',
    name: 'CommaMaximalist',
    blurb: 'a comma, after, every, word',
    mediaType: 'text',
    tags: ['punctuation-positive'],
    spec: `insert a comma and a space after every word.
the file gets larger.
the file reads aloud as if catching its breath.`,
    ratio: '~1.4×',
    lossiness: 'creative',
    status: 'algorithm',
  },
  {
    id: 'alt-text-only',
    name: 'AltText',
    blurb: 'a description of the text',
    mediaType: 'text',
    tags: ['accessibility-adjacent', 'recursive'],
    spec: `replaces the text with a description of the text.
the description is generated by a person who has not read the text.
the person is greg.`,
    ratio: 'unpredictable',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'chicago-bib',
    name: 'ChicagoBib.txt',
    blurb: 'becomes a wrong citation',
    mediaType: 'text',
    tags: ['citation', 'academic-adjacent'],
    spec: `the entire file is replaced with a single chicago-style citation of itself.
the page numbers are wrong.
the author is greg.
the year is 1996.`,
    ratio: '?',
    lossiness: 'destructive',
    status: 'spec',
    stats: { cited_by: '0 papers (1 letter to the editor)' },
  },

  // ─────────── IMAGE ───────────
  {
    id: 'average-color-jpeg',
    name: 'AverageColor.jpeg',
    blurb: 'one (1) pixel, the mean',
    mediaType: 'image',
    tags: ['mean-rgb', 'one-pixel'],
    spec: `encodes any image as a single 1×1 pixel of the mean RGB value.
decoder MUST produce a rectangle.
decoder SHOULD produce feelings.
citation needed. citation still needed.`,
    ratio: '~0.00001×',
    lossiness: 'destructive',
    status: 'algorithm',
    stats: { stars: '★ — my wedding photos are beige' },
  },
  {
    id: 'mona-lisa-png',
    name: 'MonaLisa.png',
    blurb: 'every image is the mona lisa',
    mediaType: 'image',
    tags: ['substitution', 'art-history'],
    spec: `the decoder ignores the encoded data.
the output is the mona lisa.
this is a feature.`,
    ratio: 'irrelevant',
    lossiness: 'creative',
    status: 'spec',
  },
  {
    id: 'jpeg-squared',
    name: 'JPEG²',
    blurb: 'JPEG, fifty times',
    mediaType: 'image',
    tags: ['generation-loss', 'iterative'],
    spec: `recompress the input as JPEG quality 18 fifty (50) times.
the image acquires a personality.
the personality is sad.`,
    ratio: '~0.4× (and worse)',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'where-waldo-gif',
    name: 'WhereWaldo.gif',
    blurb: 'keeps only waldo',
    mediaType: 'image',
    tags: ['subject-extraction', 'larger-output'],
    spec: `the encoder removes everything except waldo.
the file size increases.
if waldo is not present the file is empty.
the file is mostly empty.`,
    ratio: '1.8×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'one-edge-svg',
    name: 'OneEdge.svg',
    blurb: 'the strongest edge, that is all',
    mediaType: 'image',
    tags: ['edge-detection', 'svg-output'],
    spec: `detect the single strongest edge in the image.
emit it as an svg path.
discard the rest.
the rest was nothing.`,
    ratio: '~0.001×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'paint-fill-bmp',
    name: 'PaintFill.bmp',
    blurb: 'a single bucket fill',
    mediaType: 'image',
    tags: ['ms-paint-adjacent', 'flood-fill'],
    spec: `pick a random pixel.
fill the entire image with its color.
save as bitmap.
do not save as anything else.`,
    ratio: '1× (uncompressed bmp)',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'nsfw-blur',
    name: 'NSFWBlur.exe',
    blurb: 'blurs everything, just in case',
    mediaType: 'image',
    tags: ['blur', 'precautionary'],
    spec: `applies a 60px gaussian blur to the entire image.
the algorithm considers all images nsfw.
the algorithm is correct.`,
    ratio: '1×',
    lossiness: 'lossy',
    status: 'algorithm',
  },
  {
    id: 'downsample-no-upscale',
    name: 'DownsampleOnly.png',
    blurb: '8×8 forever',
    mediaType: 'image',
    tags: ['downsample', 'no-restoration'],
    spec: `nearest-neighbor downsample to 8×8 pixels.
do not upscale.
the decoder does not upscale.
the decoder also returns 8×8.`,
    ratio: '~0.0001×',
    lossiness: 'destructive',
    status: 'algorithm',
  },

  // ─────────── AUDIO ───────────
  {
    id: 'mp2',
    name: 'MP2',
    blurb: 'MP3 minus one',
    mediaType: 'audio',
    tags: ['mp-family', 'subtraction'],
    spec: `identical to MP3 but the number is smaller.
listening MAY cause loss of hearing in one (1) eye.`,
    ratio: '~0.94× (one less)',
    lossiness: 'lossy',
    status: 'spec',
    stats: { stars: '★★★★★ — i cant hear out of one eye' },
  },
  {
    id: 'vinyl-sim',
    name: 'VinylSim.flac',
    blurb: '20MB of added crackle',
    mediaType: 'audio',
    tags: ['enlarging', 'analog-adjacent'],
    spec: `the audio is preserved.
twenty (20) megabytes of vinyl crackle is appended.
the file is now warmer.`,
    ratio: '~1.4× (warmer)',
    lossiness: 'creative',
    status: 'algorithm',
  },
  {
    id: 'echo-only',
    name: 'EchoOnly.aac',
    blurb: 'the original is removed',
    mediaType: 'audio',
    tags: ['delay-keep', 'origin-remove'],
    spec: `apply a 400ms echo to the audio.
keep only the echo.
discard the source.`,
    ratio: '~1.05× (the echo)',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'vox-only',
    name: 'BreathOnly.wav',
    blurb: 'only the breath sounds',
    mediaType: 'audio',
    tags: ['vocal-isolation', 'inverse'],
    spec: `keep only the inhales, exhales, and lip smacks.
remove everything else.
remix as an album.`,
    ratio: '~0.05×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'yodel-opus',
    name: 'Yodel.opus',
    blurb: 'all audio is now yodeling',
    mediaType: 'audio',
    tags: ['substitution', 'alpine'],
    spec: `replace any audio with proportional-length yodeling.
podcasts MUST be yodeled.
voicemails MUST be yodeled.
the yodeler is unionized.`,
    ratio: '1× (proportional)',
    lossiness: 'creative',
    status: 'spec',
  },
  {
    id: 'hold-music-ogg',
    name: 'HoldMusic.ogg',
    blurb: 'becomes hold music',
    mediaType: 'audio',
    tags: ['waiting', 'corporate-adjacent'],
    spec: `replace the audio with telephone hold music.
the hold music is by kenny g.
the kenny g is licensed.
the licensor is greg.`,
    ratio: '1×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'mono-thrice',
    name: 'MonoMonoMono.mp3',
    blurb: 'mono\'d three times',
    mediaType: 'audio',
    tags: ['channel-collapse', 'redundant'],
    spec: `downmix stereo to mono.
downmix that mono to mono.
downmix that mono to mono.
the audio is now thoroughly mono.`,
    ratio: '~0.5×',
    lossiness: 'lossy',
    status: 'algorithm',
  },

  // ─────────── VIDEO ───────────
  {
    id: 'worst-frame-mp4',
    name: 'OneFrame.mp4',
    blurb: 'the worst frame',
    mediaType: 'video',
    tags: ['worst-of', 'still'],
    spec: `analyze every frame.
select the worst one.
return it.
the criteria for "worst" are subjective and not negotiable.`,
    ratio: '~0.0003×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'ascii-flipbook-pdf',
    name: 'ASCIIFlipbook.pdf',
    blurb: 'video as a flippable pdf',
    mediaType: 'video',
    tags: ['ascii-art', 'pdf-output'],
    spec: `convert every frame to 80×24 ascii.
emit as a pdf, one frame per page.
file size increases substantially.
you can print it.`,
    ratio: '~12×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'cinemascope-only',
    name: 'CinemaScope.mp4',
    blurb: '99% black bars',
    mediaType: 'video',
    tags: ['letterbox', 'aspect-ratio'],
    spec: `crop the video to a 32:1 aspect ratio.
the content is a thin strip across the middle.
the rest is black bars.
the bars are the point.`,
    ratio: '~0.05×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'commentary-track',
    name: 'CommentaryOnly.mp4',
    blurb: 'removes the video',
    mediaType: 'video',
    tags: ['audio-only', 'dvd-adjacent'],
    spec: `discard the video stream.
keep only the audio.
the audio is now the film.`,
    ratio: '~0.1×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'cuts-only-gif',
    name: 'CutsOnly.gif',
    blurb: 'one frame per cut',
    mediaType: 'video',
    tags: ['scene-detection', 'gif-output'],
    spec: `detect every shot boundary.
keep one frame per shot.
emit as a gif at 1 fps.
the film is now a slideshow.`,
    ratio: '~0.002×',
    lossiness: 'destructive',
    status: 'algorithm',
  },

  // ─────────── 3D ───────────
  {
    id: 'stl-recipe',
    name: 'STL→Recipe',
    blurb: 'baking instructions',
    mediaType: '3d',
    tags: ['interpretation', 'food'],
    spec: `parse the STL mesh.
convert to step-by-step baking instructions.
preheat to 350°F.
results vary.
the oven is greg.`,
    ratio: 'depends on flour',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'stl-haiku',
    name: 'STL→Haiku',
    blurb: 'a 5-7-5 of the mesh',
    mediaType: '3d',
    tags: ['interpretation', 'poetry'],
    spec: `read the STL.
emit one haiku that summarizes its volume.
the haiku is in english.
the haiku is wrong.`,
    ratio: '~0.0001×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'stl-vertex-bag',
    name: 'STL→VertexBag.csv',
    blurb: 'vertices in a heap',
    mediaType: '3d',
    tags: ['vertex-list', 'no-topology'],
    spec: `extract all vertices.
emit as a csv (x, y, z).
discard all face information.
the order is shuffled.`,
    ratio: '~0.4×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'stl-frontview',
    name: 'STL→FrontView.jpg',
    blurb: 'one angle, flattened',
    mediaType: '3d',
    tags: ['projection', 'orthographic'],
    spec: `render an orthographic projection of the mesh from the front.
encode as jpeg quality 18.
nothing else is preserved.
do not rotate the model.`,
    ratio: '~0.02×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'obj-to-ikea',
    name: 'OBJ-to-IKEA',
    blurb: 'flat-pack assembly diagrams',
    mediaType: '3d',
    tags: ['exploded-view', 'instructions'],
    spec: `decompose the mesh into convex pieces.
emit a 6-page pdf of exploded diagrams with no text.
include one (1) hex wrench.
the wrench is wrong size.`,
    ratio: '?',
    lossiness: 'creative',
    status: 'spec',
  },
  {
    id: 'voxel-shrink',
    name: 'VoxelShrink',
    blurb: '4×4×4 voxel grid',
    mediaType: '3d',
    tags: ['voxelize', 'destructive-downsample'],
    spec: `rasterize the mesh into a 4×4×4 voxel grid.
emit 64 (sixty-four) bits.
the bunny is now a cube.
the cube is also greg.`,
    ratio: '~0.00001×',
    lossiness: 'destructive',
    status: 'algorithm',
  },

  // ─────────── DOCUMENT ───────────
  {
    id: 'pdf-loop',
    name: 'PDF↔Word',
    blurb: 'pdf → word → pdf → word',
    mediaType: 'document',
    tags: ['round-trip', 'format-conversion'],
    spec: `convert pdf to word.
convert that word back to pdf.
convert that pdf to word again.
return the version with the most font substitutions.`,
    ratio: '~1.3×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'powerpoint-title-only',
    name: 'PowerPointTitle.pptx',
    blurb: 'keeps only the title slide',
    mediaType: 'document',
    tags: ['slide-deck', 'reduction'],
    spec: `discard all slides except the first.
remove all speaker notes.
the deck is now the deck.`,
    ratio: '~0.003×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'excel-evap',
    name: 'ExcelEvap.xlsx',
    blurb: 'formulas evaporate',
    mediaType: 'document',
    tags: ['spreadsheet', 'formula-loss'],
    spec: `delete every formula.
keep the cell positions.
the cells are now empty.
the positions remain.`,
    ratio: '~0.1×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'outline-only-pdf',
    name: 'OutlineOnly.pdf',
    blurb: 'just the table of contents',
    mediaType: 'document',
    tags: ['toc-extract', 'structure-only'],
    spec: `extract the table of contents.
discard every page.
the page numbers point nowhere.`,
    ratio: '~0.04×',
    lossiness: 'destructive',
    status: 'algorithm',
  },
  {
    id: 'page-per-word',
    name: 'PagePer.pdf',
    blurb: 'one page per word',
    mediaType: 'document',
    tags: ['enlarging', 'page-explosion'],
    spec: `split the document so each page contains one word.
center the word.
the file is now substantial.`,
    ratio: '~80×',
    lossiness: 'lossless',
    status: 'algorithm',
  },

  // ─────────── DATA ───────────
  {
    id: 'csv-novel',
    name: 'CSV→Novel.txt',
    blurb: 'a sad short story',
    mediaType: 'data',
    tags: ['interpretation', 'narrative'],
    spec: `take any csv.
write a sad short story about the data.
the protagonist is row 1.
the protagonist is also row 1.
they do not speak.`,
    ratio: '~3×',
    lossiness: 'creative',
    status: 'spec',
  },
  {
    id: 'json-apology',
    name: 'JSON→Apology',
    blurb: 'becomes a written apology',
    mediaType: 'data',
    tags: ['restructuring', 'contrition'],
    spec: `replace the json with a sincere letter of apology.
the apology is addressed to the original sender of the json.
the apology is signed by greg.
greg did not write it.`,
    ratio: '~1.1×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'xml-yelling',
    name: 'XML→Yelling',
    blurb: 'tags are shouted aloud',
    mediaType: 'data',
    tags: ['markup-removal', 'audio-output'],
    spec: `parse the xml.
emit a wav file of someone yelling each tag name.
discard the attributes.
the someone is greg.
greg is hoarse.`,
    ratio: '~12×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'proto-vibes',
    name: 'ProtoBuf→Vibes',
    blurb: 'a feeling instead',
    mediaType: 'data',
    tags: ['serialization', 'mood'],
    spec: `parse the protobuf.
emit a single english word describing the feeling.
the word is sometimes "fine".
the word is usually "no".`,
    ratio: '~0.001×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'regex-asterisk',
    name: 'RegexAlgo',
    blurb: 'compresses anything to ".*"',
    mediaType: 'data',
    tags: ['lossy-as-policy', 'two-bytes'],
    spec: `any input is replaced with the two-byte string ".*"
the decoder MUST hallucinate plausibly.
the decoder hallucinates "greg".`,
    ratio: 'literally anything → 2 bytes',
    lossiness: 'destructive',
    status: 'algorithm',
  },

  // ─────────── META ───────────
  {
    id: 'schrodinger-7z',
    name: 'Schrödinger.7z',
    blurb: 'present and not, until clicked',
    mediaType: 'meta',
    tags: ['quantum-adjacent', 'observer-effect'],
    spec: `the file exists in a superposition of present and not.
upon opening the wave function collapses.
it collapses to not.`,
    ratio: '50:50',
    lossiness: 'undefined',
    status: 'spec',
  },
  {
    id: 'procrastinator',
    name: 'Procrastinator',
    blurb: 'ten seconds, then nothing changes',
    mediaType: 'meta',
    tags: ['honest', 'time-only'],
    spec: `display a loading bar for ten (10) seconds.
return the input unchanged.
file size: unchanged.
the only honest format here.`,
    ratio: '1× (exact)',
    lossiness: 'lossless',
    status: 'algorithm',
  },
  {
    id: 'crypti-zip',
    name: 'CRYPTI-ZIP',
    blurb: 'cannot be opened without weeping',
    mediaType: 'meta',
    tags: ['emotional-encryption'],
    spec: `the archive is encrypted with the user's tears.
no tears, no extraction.
the encryption is otherwise standard.`,
    ratio: 'unchanged',
    lossiness: 'lossless',
    status: 'spec',
  },
  {
    id: 'ship-of-theseus-zip',
    name: 'ShipOfTheseus.zip',
    blurb: 'each byte replaced one at a time',
    mediaType: 'meta',
    tags: ['identity', 'gradual'],
    spec: `every hour, one byte of the file is replaced with a different byte.
after enough hours the file is a different file.
it is still the same file.
the philosophers are arguing.`,
    ratio: '1×',
    lossiness: 'lossy',
    status: 'spec',
  },
  {
    id: 'paperweight-exe',
    name: 'PaperWeight.exe',
    blurb: 'prints, scans, returns the scan',
    mediaType: 'meta',
    tags: ['analog-roundtrip', 'requires-printer'],
    spec: `the file is sent to the printer.
the printed page is scanned back in.
that scan is the output.
the original is recycled.
greg pulls it from the recycling.`,
    ratio: '~1.2×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'quantum-tar',
    name: 'Quantum.tar',
    blurb: 'may or may not exist',
    mediaType: 'meta',
    tags: ['quantum-adjacent', 'absence'],
    spec: `the file's existence is probabilistic.
the probability is unspecified.
the probability changes when you look at the directory.
do not look at the directory.`,
    ratio: '?',
    lossiness: 'undefined',
    status: 'spec',
  },
  {
    id: 'time-travel-compression',
    name: 'TimeTravelCompression',
    blurb: 'decompress arrives before compress',
    mediaType: 'meta',
    tags: ['acausal', 'impossible'],
    spec: `when you call compress(), the output is already at the destination.
the input is then deleted to balance the timeline.
the timeline is not balanced.`,
    ratio: '?',
    lossiness: 'undefined',
    status: 'spec',
  },
  {
    id: 'consciousness-compression',
    name: 'ConsciousnessCompression',
    blurb: 'only readable by the original author',
    mediaType: 'meta',
    tags: ['private', 'biometric'],
    spec: `the file may only be read by the person who created it.
the criteria for "person" are not specified.
greg has been refused access to his own files.`,
    ratio: '1×',
    lossiness: 'lossless',
    status: 'spec',
  },
  {
    id: 'apology-zip',
    name: 'Apology.zip',
    blurb: 'replaces the file with an apology',
    mediaType: 'meta',
    tags: ['contrition', 'replacement'],
    spec: `the file is deleted.
in its place is a brief written apology.
the apology is from greg.
greg did not delete the file.`,
    ratio: '~0.0001×',
    lossiness: 'destructive',
    status: 'spec',
  },
  {
    id: 'fmt-884',
    name: 'fmt#884',
    blurb: 'nobody knows',
    mediaType: 'meta',
    tags: ['mystery', 'basement'],
    spec: `it is in the basement.
it is requesting water.
do not feed.
do not approach.`,
    ratio: '?:?',
    lossiness: 'undefined',
    status: 'spec',
    stats: { complaints: '1 (it is the file)' },
  },
  {
    id: 'golden-ratio-zip',
    name: 'GoldenRatio.zip',
    blurb: 'resizes the file to phi',
    mediaType: 'meta',
    tags: ['mathematical', 'aesthetic'],
    spec: `the file is resized so its byte length is φ (1.618...).
since the byte length cannot be 1.618, the file is now empty.
the emptiness is beautiful.`,
    ratio: 'exactly φ:1',
    lossiness: 'destructive',
    status: 'spec',
  },
]
